#!/usr/bin/python3
if __name__ != '__main__':
    raise RuntimeError

import os
import sys
import argparse
import logging
log = logging.getLogger("bootmgrcfg")

version = 0.1

LEFT_PADDING = 8
RIGHT_PADDING = 8
DEFAULT_HELP_WIDTH = 80

from bootcfgmgr.loaders import loaders, getLoader

def parseArguments():
    ap = argparse.ArgumentParser()

    ap.add_argument('--version', action='version', version="%(prog)s " + str(version))
    ap.add_argument('--bootloader', dest="loadername")
    ap.add_argument('--default-kernel', dest="defaultkernel")

    # these should be last so nothing can register some other argument name
    # as a bootloader name in a plugin.
    for loader in loaders.keys():
        try:
            ap.add_argument('--%s' % (loader,), dest="loadername", action="store_const", const=loader)
        except:
            pass
    return ap.parse_args()

if __name__ == '__main__':
    log.addHandler(logging.StreamHandler(stream=sys.stdout))

    args = parseArguments()

    bl = None
    if args.loadername:
        bl = getLoader(args.loadername)
    if not args.loadername:
        for loader in loaders.keys():
            l = getLoader(loader)
            if l.compatible() and l.find_config():
                bl = l
                break
    if bl is None:
        log.error("No bootloader type specified and none could be guessed.")
