#!/usr/bin/python3
if __name__ != '__main__':
    raise RuntimeError

import os
import sys
import argparse
import logging
log = logging.getLogger("bootmgrcfg")

version = 0.1

LEFT_PADDING = 8
RIGHT_PADDING = 8
DEFAULT_HELP_WIDTH = 80

from bootcfgmgr.loaders import loaders, getLoader

def parseArguments():
    ap = argparse.ArgumentParser()

    ap.add_argument('--version', action='version', version="%(prog)s " + str(version))
    ap.add_argument('--bootloader', dest="loaderName")
    ap.add_argument('--default-kernel', dest="defaultKernel", action="store_true")
    ap.add_argument('-c', '--config-file', dest='configFile')
    ap.add_argument('--efi', dest='forceEfi', action="store_true")

    # these should be last so nothing can register some other argument name
    # as a bootloader name in a plugin.
    for loader in loaders.keys():
        try:
            ap.add_argument('--%s' % (loader,), dest="loaderName", action="store_const", const=loader)
        except:
            pass
    return ap.parse_args()

if __name__ == '__main__':
    log.addHandler(logging.StreamHandler(stream=sys.stdout))

    args = parseArguments()

    bl = None
    if args.loaderName:
        bl = getLoader(args.loaderName)
    if not args.loaderName:
        for loader in loaders.keys():
            l = getLoader(loader)
            if hasattr(l, 'forceEfi'):
                l.forceEfi = True
            if l.compatible and l.find_config(args.configFile):
                bl = l
                break
            del l
    if bl is None:
        log.error("No bootloader type specified and none could be guessed.")
        sys.exit(1)

    # handle actions we're told to use:
    if args.defaultKernel:
        found = False
        for x in range(0, len(bl.stanzas)):
            if bl.stanzas[x].default:
                print("%d", x)
                found = True
                break
        if not found:
            print("-1")
